### ISSUE TITLE
Screenshot, install instructions

### ISSUE THREAD

**Issue by PySimpleGUI** [wkiino/hyper_to_rgb#1]
Hi!

Screenshot

Thank you very much for including a screenshot in your readme!  This is SO helpful to visitors.  It grabs people's attention because SO few Python programs have a GUI.  You worked hard to make a GUI so why not show it to people?  Nice work.

Install

You may want to add that PySimpleGUI needs to be installed as well in your installation instructions?  Actually, now that I see your requirements.txt, there are a good number of packages that have to be installed.

colour==0.1.5
colour-science==0.3.15
japanize-matplotlib==1.0.5
matplotlib==3.2.1
numpy==1.18.1
Pillow==7.0.0
PySimpleGUI==4.16.0
scikit-image==0.16.2

I would recommend upgrading to the latest PySimpleGUI (4.19.0) if you can.

Of course none of these are very important things and you can ignore them all.  I mostly wanted to say thanks for using PySimpleGUI and for posting a screenshot.  It's a nice looking app you've made!

**Comment by hideo130** [comment]
Thanks for your comments and advice.
Upgraded according to your advice.
